# Generated by Django 2.2.6 on 2019-12-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcap',
            name='json_data',
            field=models.CharField(default='', max_length=40000),
        ),
    ]
